# Generated by Django 3.0.7 on 2020-06-06 07:04

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0004_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truecaller.RegisterUsers')),
            ],
            options={
                'unique_together': {('name', 'phone_number')},
            },
        ),
    ]
