# Generated by Django 3.0.7 on 2020-06-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0005_peopledetails'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peopledetails',
            unique_together=set(),
        ),
    ]
