# Generated by Django 3.0.7 on 2020-06-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller', '0006_auto_20200606_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopledetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
